// Generated Supabase database types.
//
// This file is auto-generated by `npm run db:types` from the local database
// schema. It is checked in so the app stays typed even if a developer hasn't
// run `db:types` locally. Re-generate after every migration:
//
//   npm run db:start
//   npm run db:reset
//   npm run db:types
//
// Until M1 introduces the first table, the database is empty and this stub
// exports an empty type so `Database["public"]["Tables"]` resolves cleanly.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
